#!/bin/bash

RUSTFLAGS='-C target-cpu=native'  cargo build --release
# RUSTFLAGS='-C target-cpu=native'  cargo run --release -- $@
# RUSTFLAGS='--emit asm -C target-cpu=native' cargo bench -- $@

# gcloud compute instances create instance-1 --project=omphalos-1186 --zone=us-central1-c --machine-type=n2-standard-16 --network-interface=network-tier=PREMIUM,subnet=default --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=438246618084-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --min-cpu-platform=Intel\ Ice\ Lake --create-disk=auto-delete=yes,boot=yes,device-name=instance-1,image=projects/debian-cloud/global/images/debian-10-buster-v20220118,mode=rw,size=10,type=projects/omphalos-1186/zones/us-east4-b/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
